#dicionario com probeid e continente?# Criação do dicionário
probesLocation = {
    7126: {"país": "Tailândia", "continente": "Ásia"},
    16012: {"país": "Reino Unido", "continente": "Europa"},
    54441: {"país": "Reino Unido", "continente": "Europa"},
    55023: {"país": "Reino Unido", "continente": "Europa"},
    1006226: {"país": "Tailândia", "continente": "Ásia"},
    11813: {"país": "Reino Unido", "continente": "Europa"},
    1006068: {"país": "Estados Unidos", "continente": "América do Norte"},
    62657: {"país": "Canadá", "continente": "América do Norte"},
    14390: {"país": "Japão", "continente": "Ásia"},
    15961: {"país": "Estados Unidos", "continente": "América do Norte"},
    19709: {"país": "México", "continente": "América do Norte"},
    28310: {"país": "França", "continente": "Europa"},
    33319: {"país": "Países Baixos", "continente": "Europa"},
    33977: {"país": "França", "continente": "Europa"},
    51237: {"país": "França", "continente": "Europa"},
    51924: {"país": "Índia", "continente": "Ásia"},
    52123: {"país": "Canadá", "continente": "América do Norte"},
    53099: {"país": "Índia", "continente": "Ásia"},
    55313: {"país": "Canadá", "continente": "América do Norte"},
    55492: {"país": "Canadá", "continente": "América do Norte"},
    55630: {"país": "Estados Unidos", "continente": "América do Norte"},
    60345: {"país": "Países Baixos", "continente": "Europa"},
    1001877: {"país": "Japão", "continente": "Ásia"},
    1003641: {"país": "Tailândia", "continente": "Ásia"},
    1004979: {"país": "México", "continente": "América do Norte"},
    1005021: {"país": "México", "continente": "América do Norte"},
    1006146: {"país": "Índia", "continente": "Ásia"},
    1006361: {"país": "França", "continente": "Europa"},
    1007949: {"país": "Países Baixos", "continente": "Europa"},
    1004383: {"país": "Japão", "continente": "Ásia"}
}
